name: Build GCC

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    name: Build GCC
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive' 
      - name: Download pre-requisites
        run: cd gcc && contrib/download_prerequisites
      - name: Configure GCC
        run: |
          mkdir gcc/build && cd gcc/build
          ../configure --prefix=/usr/local/gcc-10 \
            --enable-checking=release \
            --enable-languages=c,c++,fortran \
            --enable-decimal-float=bid
            --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk \
            --program-suffix=-10
      - name: Build gcc
        run: |
          cd gcc/build
          make -j 8
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            gcc/build
          name: Build